details = [
  {"name": "Alice", "age": 25, "city": "New York"},
  {"name": "Bob", "age": 30, "city": "San Francisco"},
  {"name": "Charlie", "age": 35, "city": "Chicago"},
  {"name": "David", "age": 28, "city": "Seattle"},
  {"name": "Eve", "age": 22, "city": "Boston"},
  {"name": "Frank", "age": 31, "city": "Los Angeles"},
  {"name": "Grace", "age": 27, "city": "Austin"},
  {"name": "Hannah", "age": 29, "city": "Denver"},
  {"name": "Ivy", "age": 24, "city": "Portland"},
  {"name": "Jack", "age": 33, "city": "Miami"},
  {"name": "Karen", "age": 26, "city": "Houston"},
  {"name": "Leo", "age": 34, "city": "Phoenix"},
  {"name": "Mia", "age": 23, "city": "San Diego"},
  {"name": "Nina", "age": 32, "city": "Dallas"},
  {"name": "Oscar", "age": 35, "city": "Atlanta"},
  {"name": "Paul", "age": 28, "city": "Orlando"},
  {"name": "Quinn", "age": 21, "city": "Las Vegas"},
  {"name": "Rachel", "age": 29, "city": "Tampa"},
  {"name": "Sam", "age": 25, "city": "Chicago"},
  {"name": "Tina", "age": 30, "city": "New Orleans"},
  {"name": "Uma", "age": 27, "city": "Memphis"},
  {"name": "Victor", "age": 26, "city": "Baltimore"},
  {"name": "Wendy", "age": 31, "city": "San Jose"},
  {"name": "Xander", "age": 33, "city": "Sacramento"},
  {"name": "Yara", "age": 22, "city": "Salt Lake City"},
  {"name": "Zack", "age": 34, "city": "Columbus"},
  {"name": "Amy", "age": 25, "city": "Charlotte"},
  {"name": "Ben", "age": 30, "city": "Indianapolis"},
  {"name": "Cathy", "age": 35, "city": "Cincinnati"},
  {"name": "Don", "age": 28, "city": "Kansas City"},
  {"name": "Ella", "age": 22, "city": "Milwaukee"},
  {"name": "Fred", "age": 31, "city": "Pittsburgh"},
  {"name": "Gina", "age": 27, "city": "St. Louis"},
  {"name": "Harry", "age": 29, "city": "Detroit"},
  {"name": "Isla", "age": 24, "city": "Cleveland"},
  {"name": "Joe", "age": 33, "city": "Raleigh"},
  {"name": "Kate", "age": 26, "city": "Richmond"},
  {"name": "Liam", "age": 34, "city": "Buffalo"},
  {"name": "Mona", "age": 23, "city": "Birmingham"},
  {"name": "Nick", "age": 32, "city": "Anchorage"},
  {"name": "Olivia", "age": 35, "city": "Honolulu"},
  {"name": "Pete", "age": 28, "city": "Boise"},
  {"name": "Queen", "age": 21, "city": "Little Rock"},
  {"name": "Ron", "age": 29, "city": "Des Moines"},
  {"name": "Sara", "age": 25, "city": "Fargo"},
  {"name": "Tom", "age": 30, "city": "Madison"},
  {"name": "Ursula", "age": 27, "city": "Spokane"},
  {"name": "Violet", "age": 26, "city": "Charleston"},
  {"name": "Will", "age": 31, "city": "Fort Worth"},
  {"name": "Xena", "age": 33, "city": "El Paso"}
]


for x in details:
    print

  
print (result)
